### PR TITLE
Recursive Multiple ColumnGroups

### PR DESCRIPTION
**Pull request by ladriangb**
Hello,

I have this change almost ready but it has still some bugs like: Pinning and Resizing but it should be ready in a few time

you can see it http://jsfiddle.net/adrian_and1/dhngso12/

### CODE REVIEW

**Comment by ladriangb** [comment]
Fix Recursive Multiple ColumnGroups #173  issue

**Comment by ceolter** [comment]
Thanks for the PR. I haven't looked into the details of the code, however I do notice that you checked in the contents of /dist and /docs/dist. Can you revet the changes to these files? The process is, everything except these files get modified, and then when ready for a release, I do one gulp run and check in the dist files into master and do a git release. Let me know when the PR is done and I'll take a proper look. When I did the first pass of this, it took me a lot of thinking and working through patterns to get it working, so am expecting what your are working on to be pretty tricky and requiring a good code review by me!

**Comment by ceolter** [comment]
have had a quick look at this just now - the column resize doesn't appear to work - should this be working? thanks :)

**Comment by ladriangb** [comment]
right now this is a bug in the application but I'm correcting it,
other bugs that are getting pinned colums and the expandable columns that I have almost ready in a couple of days so you can review.

**Comment by ladriangb** [comment]
Hi I think that is ready please check it and give me a feedback 

tk

**Comment by ceolter** [comment]
thanks for forwarding. will prob be the weekend before i get a chance, as i want to give it proper time for a full code review. thanks :)

**Comment by gjdev** [comment]
Does this still have a chance of getting merged?

**Comment by ceolter** [comment]
i was going to code review your change, and then merge it manually (as i'll probably make a lot of changes to it). i wasn't going to merge as is. so if it's not merging with the new version (which it isn't i think) then don't worry about it (unless you want to merge it for yourself).

i do apologies, i've a lot on my plate.

**Comment by surjikal** [comment]
Would be interesting if this branch was updated to the latest master.

**Comment by ceolter** [comment]
i have implemented multi level column groups in v3 branch. this will be in the next release.

**Pull request closed without merging**
