### PR TITLE
Add ag-hover when row is hovered

### PR DESCRIPTION
**Pull request by MikaAK**
I know there is definitely a better way to achieve this to maintain the style of this code repo, but I wasn't quite sure how so, I put a quick fix for work!. This solves #223.

If you could provide guidance on how to fix up the code so it fits the correct style I would be happy to change it up.

### CODE REVIEW

**Comment by ceolter** [comment]
thanks for the PR. i'll take a look shortly.

**Comment by antur84** [comment]
There's a small issue with this fix, if you enter edit mode in a cell using a custom cellRenderer, the hover event triggers again and adds the hover class to the row a second time.

I added a simple check for it in https://github.com/antur84/ag-grid/commit/5204a19d21d08420cb6307cf6ec4ae66088ac483

**Comment by ceolter** [comment]
i haven't had a chance to look. the last few weeks of my life have been mental :( . . . . i've left the PR open though, in time i'll either accept this PR or have it implemented another way before closing.

**Comment by antur84** [comment]
Yeah no worries, I cherry picked it into my fork and noticed the issue,
just wanted to point out what I found :)

2015-10-23 16:19 GMT+02:00 Niall Crosby <notifications@github.com>:

**Pull request closed without merging**
