### PR TITLE
Change for angular2@2.0.0-beta.0

### PR DESCRIPTION
**Pull request by TeeNak**
Made it work both with angular2-alpha and angular2-beta.
Note that we have to change the markup when working with angular2-beta like this
[From]
```
    [column-defs]="columnDefs"
    [row-data]="rowData"
```
[To]
```
    [columnDefs]="columnDefs"
    [rowData]="rowData"
```
because of the kebab-case removal in angular2.
https://github.com/angular/angular/commit/da9b46a

### CODE REVIEW

**Comment by ceolter** [comment]
Thanks for the info. I've just checked in these changes. I took influence from you comments and your pull request, however I made the change myself as I wanted to go through the trial and error of learning Angular 2 - also I don't want to support older versions. All along, as different alphas were coming out, I was programming to the latest as changes happened. If I was to support all the alphas and betas, the code would be just to messy for no real gain.

**Comment by TeeNak** [comment]
I just worried about npm semver rules which requires backword compatibility.
Yes but it's alpha, I think you don't have to support alpha any longer.
Keep moving :-)

**Comment by ceolter** [comment]
npm rules, really? what is the rule?

so if i want to make a change that is not backward compatible, which part of the version number am i allowed to change?

**Comment by TeeNak** [comment]
This is the semver rules adopted by npm.
http://semver.org/
```
8. Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.
```
So strictly saying, you have to change the major version number when you introduce a backwards incompatible change.

**Pull request closed without merging**
