### PR TITLE
Rename PopupService.js to popupService.js

### PR DESCRIPTION
**Pull request by kayue**

### CODE REVIEW

**Comment by ceolter** [comment]
i don't understand what's happening here. i have already changed the file from upper case to lower case.

see here:
https://github.com/ceolter/ag-grid/tree/master/src/ts/widgets

maybe you are working off an old version?

**Comment by kayue** [comment]
@ceolter But the file in `dist` directory aren't being updated.

I got the following error when compiling it.

```
Unhandled rejection Error on fetch for github:ceolter/ag-grid@4.0.5/dist/lib/widgets/popupService at file:///home/hype/hypebeast/releases/20160405102258/src/Hypebeast/Bundle/WarehouseBundle/Resources/public/jspm_packages/github/ceolter/ag-grid@4.0.5/dist/lib/widgets/popupService.js
```

**Comment by kayue** [comment]
@ceolter Please consider merging this, otherwise people could not build their app...

**Comment by ceolter** [comment]
i have just fixed this and released 4.0.6.

advise if the problem is not fixed. thanks.

**Pull request closed without merging**
