### PR TITLE
addition of getRowsAfterFilter to the api.getModel

### PR DESCRIPTION
**Pull request by christoffee**
##### the change is 'src/ts/rowControllers/inMemoryRowController.ts' (the other changes are from the build)

So i added it to model so that i could get the rows that hadn't been filtered out as the array already exists.

I was using it for exporting data from the table.

Is this right?

### CODE REVIEW

**Comment by christoffee** [comment]
the change is 'src/ts/rowControllers/inMemoryRowController.ts'

**Comment by ceolter** [comment]
ah, you want to get the rows after the filter, where'as 'getVirtualRowCount' and 'getVirtualRow' show you what's displayed (so can have rows missing if your grouping and some groups are closed).

**Comment by christoffee** [comment]
yh exactly... is adding getRowsAfterFilter the best way to do it?

**Comment by ceolter** [comment]
am not sure . . . . as the data you get back will be grouped . . . . . might be better if i provide way that returned a flat list - like what you give the grid.

**Comment by ceolter** [comment]
closing this as you can now achieve this with the api.forEachNodeAfterFilter() method.

**Pull request closed without merging**
