### PR TITLE
fix: avoid global declaration of module variable

### PR DESCRIPTION
**Pull request by S-YOU**

### CODE REVIEW

**Comment by ceolter** [comment]
same here, this wont work. it needs to reference the variable provided by commonjs, not declare a new one.

these mean different things:
declare var i; // tell typescript about a variable that already exists, so no compile errors.
var i; // declare a new variable

**Comment by S-YOU** [comment]
re-declaration does not overwrite the origin value in javascript, 
but you are right, it isn't usable inside closure. closing.

**Comment by ceolter** [comment]
i've just checked in a fix for this, i've moved to using node.d.ts

**Comment by S-YOU** [comment]
thank you, much better.

**Pull request closed without merging**
