### PR TITLE
Made autoSizeColumns() to work with cells headers

### PR DESCRIPTION
**Pull request by mpetkov**
Added support, inside the autoWidthCalculator, to calculate the width based on the header as well as the cell.

### CODE REVIEW

**Comment by ceolter** [comment]
interesting. thanks. will take a look when i get a chance.

**Comment by mikeerickson** [comment]
+1 Yes Please :-)

**Comment by arkon** [comment]
Any update on this? Seems like an obvious feature to have.

**Comment by ceolter** [comment]
Any update on this? Seems like an obvious feature to have.
=> yes, i plan to get it in. just very busy with pivot right now. i'm hoping to include this in the next release.

**Comment by adduss** [comment]
@ceolter when you are planning to release next version ?

**Comment by ceolter** [comment]
it didn't make release v5 :( i'm hoping to look at this tomorrow, before i go on my holidays the next day :( . . . . this is probably the feature i want most in the grid from all the small requested features.

**Comment by ceolter** [comment]
i have now implemented this. will be releasing later today. i didn't take the PR as a lot of code has changed (around how the headers work) since this PR was created.

**Pull request closed without merging**
